# ASP.NET
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - -'
      Write-Host ' reflect Azure Devops repo changes to GitHub repo'
      Write-Host ' - - - - - - - - - - - - - - - - - - - - - - - - - '$stageDir = '$(Build.SourcesDirectory)' | Split-Path
      $githubDir = $stageDir +"\"+"gitHub"
      $destination = $githubDir +"\"+"AddressBook.git"#please provide your username
      $alias = 'Sam Lee:'+ "$(Github.PAT)"
      $sourceURL = 'https://$(AzureDevOps.PAT)@ProjectHubBuddies@dev.azure.com/ProjectHubBuddies/AddressBook/_git/AddressBook'
      $destURL = 'https://' + $alias + '@github.com/hboiled/AddressBook.git'#Check if the parent directory exists and delete
      if((Test-Path -path $githubDir))
      {
        Remove-Item -Path $githubDir -Recurse -force
      }if(!(Test-Path -path $githubDir))
      {
        New-Item -ItemType directory -Path $githubDir
        Set-Location $githubDir
        git clone --mirror $sourceURL
      }
      else
      {
        Write-Host "The given folder path $githubDir already exists";
      }Set-Location $destinationWrite-Output '*****Git removing remote secondary****'
      git remote rm secondaryWrite-Output '*****Git remote add****'
      git remote add --mirror=fetch secondary $destURLWrite-Output '*****Git fetch origin****'
      git fetch $sourceURLWrite-Output '*****Git push secondary****'
      git push secondary --allWrite-Output '**Azure Devops repo synced with Github repo**'
      Set-Location $stageDirif((Test-Path -path $githubDir))
      {
       Remove-Item -Path $githubDir -Recurse -force
      }
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
