CREATE TABLE "PhoneNumbers" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"PersonId"	INTEGER NOT NULL,
	"Number"	INTEGER NOT NULL,
	"IsPrimary"	INTEGER NOT NULL,
	FOREIGN KEY("PersonId") REFERENCES "People"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
)